import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {empty,KEYS} from '../src/store.js';import {coreFixture} from './core-depth-fixture.mjs';
const base=process.env.FAITHPATH_QA_URL||'http://127.0.0.1:4203',out=process.env.FAITHPATH_QA_OUT||'qa-output/continuity/after',baseline=process.env.BASELINE==='1';fs.mkdirSync(out,{recursive:true});
const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox',...(process.env.FAITHPATH_PROXY_SPKI?['--ignore-certificate-errors-spki-list='+process.env.FAITHPATH_PROXY_SPKI]:[])]});const results=[],errors=[],consoleErrors=[],loads=[];const seed=coreFixture();seed.journal[0].ref={book:'JHN',chapter:3,from:1,to:1,translation:'otb'};seed.paths[0].reviews[0].date=new Date().toISOString();
async function context(data=seed,viewport={width:390,height:844},sw='block'){const c=await b.newContext({viewport,serviceWorkers:sw,isMobile:viewport.width<769,hasTouch:viewport.width<769});await c.addInitScript(({data,KEYS})=>{if(!sessionStorage.getItem('continuity-seeded')){localStorage.setItem(KEYS.onboard,'done');localStorage.setItem(KEYS.main,JSON.stringify(data));sessionStorage.setItem('continuity-seeded','1');}},{data,KEYS});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});p.on('response',r=>{if(r.status()>=400)loads.push({url:r.url(),status:r.status()});});return {c,p};}
async function route(p,r){await p.goto(base+'/#'+r,{waitUntil:'networkidle'});await p.locator('main h1').waitFor();if(r.startsWith('read/'))await p.locator('.verse').first().waitFor();await p.evaluate(()=>window.scrollTo(0,0));}
async function shot(p,n){if(await p.locator('.toast.error.visible [data-action="dismiss-status"]').count())await p.locator('.toast.error.visible [data-action="dismiss-status"]').click();await p.locator('.toast.visible').waitFor({state:'hidden',timeout:10000});await p.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await p.screenshot({path:path.join(out,n+'.png')});await p.screenshot({path:path.join(out,n+'-full.png'),fullPage:true});}
async function check(n,fn){try{await fn();results.push({name:n,status:'PASS'});console.log('PASS',n);}catch(e){results.push({name:n,status:'FAIL',error:e.stack});console.log('FAIL',n,e.message);}}
const states={A:empty(),B:{...empty(),reading:seed.reading},C:{...empty(),paths:[{...seed.paths[0],links:[],reviews:[],milestones:[]}]},D:{...seed,highlights:[],reviews:[]},E:seed,F:seed,G:{...seed,journal:[],reviews:[],paths:[{...seed.paths[0],reviews:[],milestones:[]}]},H:{...seed,paths:[{...seed.paths[0],id:'archived-path',archived:true},seed.paths[0]]}};
try{
 const {c,p}=await context();
 for(const [r,n]of[['today','01-today-active'],['bible','03-bible-continue'],['read/JHN/3/otb','04-reader-context'],['entry/thought-old','07-journal-context'],['path/core-path','08-path-next'],['reviews','09-reviews-pairs'],['history','10-history'],['marks','11-marks-context']]){await route(p,r);await shot(p,n);}
 await route(p,'read/JHN/3/otb');await p.locator('[data-v="1"]').click();await shot(p,'05-reader-selection');await p.getByRole('button',{name:'Markieren',exact:true}).click();await shot(p,'06-palette');await p.getByRole('dialog').getByRole('button',{name:'Schließen',exact:true}).click();
 if(!baseline){
 await check('continue reading exact link and reload',async()=>{await route(p,'bible');await p.locator('.continue-reading').waitFor();await p.getByRole('link',{name:'Weiterlesen',exact:true}).click();await p.locator('.verse').first().waitFor();assert(p.url().includes('/JHN/3/otb'));await p.reload({waitUntil:'networkidle'});await p.locator('.verse').first().waitFor();});
 await check('reader path and thought context target actual records',async()=>{await route(p,'read/JHN/3/otb');const ctx=p.locator('[data-verse-context="1"]');await ctx.waitFor();assert((await ctx.innerText()).includes('In Ruhe zuhören'));assert.equal(await ctx.locator('a[href="#path/core-path"]').count(),1);assert.equal(await ctx.locator('a[href="#entry/thought-old"]').count(),1);});
 await check('journal exposes existing later review and both dates',async()=>{await route(p,'entry/thought-old');await p.getByRole('link',{name:'Rückblick ansehen',exact:true}).click();await p.getByText(seed.reviews[0].text,{exact:true}).waitFor();await route(p,'reviews');assert((await p.locator('.continuity-pair').first().innerText()).includes('September'));});
 await check('path review is addressable without changing IDs',async()=>{await route(p,'review/path-review');await p.getByText(seed.paths[0].reviews[0].text,{exact:true}).waitFor();});
 await check('save new linked thought offers previous real thought',async()=>{await route(p,'path/core-path');await p.getByRole('button',{name:'Gedanken festhalten',exact:true}).click();await p.getByLabel('Dein Gedanke',{exact:true}).fill('Heute höre ich bewusst zu.');await p.locator('#editor-form button[type=submit]').click();await p.getByRole('link',{name:'Früheren Gedanken ansehen',exact:true}).waitFor();await p.getByRole('link',{name:'Früheren Gedanken ansehen',exact:true}).click();assert(p.url().includes('entry/thought-new'));});
 await check('backup roundtrip retains continuity links',async()=>{await route(p,'more');await p.getByRole('link',{name:'Daten & Backup',exact:false}).click();const dl=p.waitForEvent('download');await p.getByRole('button',{name:'Backup exportieren',exact:true}).click();const file=path.resolve(out,'continuity-backup.json');await (await dl).saveAs(file);await p.locator('#import-file').setInputFiles(file);await p.getByRole('button',{name:'Backup wiederherstellen',exact:true}).click();await p.waitForFunction(()=>!document.querySelector('dialog').open);await route(p,'entry/thought-old');assert.equal(await p.locator('a[href="#path/core-path"]').count(),1);});
 }
 await c.close();
 if(!baseline){const {c,p}=await context(seed,{width:390,height:844},'allow');await check('offline reload retains continuity contexts',async()=>{await route(p,'more');await p.getByRole('link',{name:'Einstellungen',exact:true}).click();await p.locator('#offline-state').filter({hasText:'Beide Bibeln und die App sind für dieses Gerät offline bereit.'}).waitFor({timeout:60000});await c.setOffline(true);await p.reload({waitUntil:'networkidle'});for(const r of['bible','entry/thought-old','review/path-review','read/JHN/3/otb']){await route(p,r);}assert.equal(await p.locator('[data-verse-context="1"] a[href="#path/core-path"]').count(),1);await shot(p,'offline-continuity');});await c.close();
 const palette=await context();await check('palette roving focus and multiple path links remain reachable',async()=>{const p=palette.p;await route(p,'read/JHN/3/otb');await p.locator('[data-v="1"]').click();await p.getByRole('button',{name:'Markieren',exact:true}).click();assert.equal(await p.locator('.color-choice[tabindex="0"]').count(),1);await p.getByRole('option',{name:'Olive',exact:true}).focus();await p.keyboard.press('ArrowRight');await p.waitForTimeout(100);assert(await p.getByRole('option',{name:'Gold',exact:true}).evaluate(el=>el===document.activeElement));await p.keyboard.press('Enter');assert.equal(await p.locator('.verse.highlight-gold').count(),1);await p.evaluate(KEYS=>{const d=JSON.parse(localStorage.getItem(KEYS.main));d.paths.push({...structuredClone(d.paths[0]),id:'second-path',title:'Zweiter Weg'});localStorage.setItem(KEYS.main,JSON.stringify(d));},KEYS);await p.reload({waitUntil:'networkidle'});await route(p,'mark/legacy-highlight');assert.equal(await p.locator('a[href="#path/second-path"]').count(),1);});await palette.c.close();}
 for(const [name,data]of Object.entries(states)){const {c,p}=await context(data);await route(p,'today');if(name==='G')await shot(p,'02-today-review-prompt');if(!baseline)await check('state '+name,async()=>{await route(p,'bible');assert.equal(await p.locator('.continue-reading').count(),data.reading?1:0);await route(p,'today');if(name==='G'){const strip=await p.locator('.continuity-reminder').boundingBox(),card=await p.locator('.personal-path').boundingBox(),recent=await p.locator('.personal-recent').boundingBox();assert(strip.y>card.y);assert(!recent||strip.y<recent.y);}if(name==='H')assert((await p.locator('.personal-path').innerText()).includes('In Ruhe zuhören'));if(name==='A'){await route(p,'reviews');assert.equal(await p.locator('.continuity-pair').count(),0);assert.equal(await p.locator('[data-action="gap"]').count(),0);}});await c.close();}
 if(!baseline){
 const dangling=structuredClone(seed);dangling.paths=[];dangling.journal[0].ref=null;dangling.highlights=[];const {c,p}=await context(dangling);await check('deleted path produces no dead links or invented pair',async()=>{await route(p,'entry/thought-old');assert.equal(await p.locator('a[href="#path/core-path"]').count(),0);await route(p,'history');assert.equal(await p.locator('.continuity-pair[data-pair-kind="shared-context"]').count(),0);});await c.close();
 for(const [w,h]of[[320,568],[768,1024],[1440,1000]]){const {c,p}=await context(seed,{width:w,height:h});await check('responsive '+w,async()=>{for(const [r,n]of[['today','today'],['bible','bible'],['read/JHN/3/otb','reader'],['reviews','reviews'],['path/core-path','path']]){await route(p,r);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),r);await shot(p,w+'-'+n);}await route(p,'read/JHN/3/otb');await p.locator('[data-v="1"]').click();await shot(p,w+'-selection');await p.getByRole('button',{name:'Markieren',exact:true}).click();await shot(p,w+'-palette');assert(await p.evaluate(()=>{const d=document.querySelector('dialog');return d.scrollWidth<=d.clientWidth;}));});await c.close();}
 for(const w of[390,320]){const {c,p}=await context(seed,{width:w,height:w===320?568:844});await check('200% text '+w,async()=>{for(const r of['today','bible','read/JHN/3/otb','entry/thought-old','path/core-path','reviews','history','marks']){await route(p,r);await p.evaluate(()=>document.documentElement.style.fontSize='200%');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),r);}await shot(p,'200-text-'+w);await route(p,'read/JHN/3/otb');await p.evaluate(()=>document.documentElement.style.fontSize='200%');await p.locator('[data-v="1"]').click();await p.getByRole('button',{name:'Markieren',exact:true}).click();assert(await p.evaluate(()=>document.querySelector('dialog').scrollWidth<=document.querySelector('dialog').clientWidth));await shot(p,'200-palette-'+w);});await c.close();}
 const zero=await context();await check('Today Compact zero-inset geometry unchanged',async()=>{await route(zero.p,'today');assert.equal((await zero.p.locator('.topbar').boundingBox()).height,70);assert.equal((await zero.p.locator('.olive-hero').boundingBox()).height,210);});await zero.c.close();const safe=await context();await check('simulated safe areas, focus and reduced motion',async()=>{const p=safe.p;await p.evaluate(()=>{document.documentElement.style.setProperty('--safe-top','47px');document.documentElement.style.setProperty('--safe-bottom','34px');});for(const r of['today','read/JHN/3/otb','reviews','path/core-path']){await route(p,r);await p.evaluate(()=>{document.documentElement.style.setProperty('--safe-top','47px');document.documentElement.style.setProperty('--safe-bottom','34px');});assert(await p.locator('.topbar').evaluate(el=>parseFloat(getComputedStyle(el).paddingTop)>=47));const nav=await p.locator('.primary-nav').boundingBox();assert(nav.y+nav.height<=844);assert(await p.locator('.primary-nav').evaluate(el=>parseFloat(getComputedStyle(el).paddingBottom)>=34));}await shot(p,'safe-area-bottom');await route(p,'today');await p.evaluate(()=>{document.documentElement.style.setProperty('--safe-top','47px');document.documentElement.style.setProperty('--safe-bottom','34px');});await shot(p,'safe-area-top');await p.emulateMedia({reducedMotion:'reduce'});await p.locator('#menu-toggle').focus();await p.keyboard.press('Enter');assert(await p.locator('#main-menu').isVisible());await p.keyboard.press('Escape');assert.equal(await p.locator('#menu-toggle').getAttribute('aria-expanded'),'false');});await safe.c.close();
 }
}finally{await b.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({base,baseline,results,errors,consoleErrors,loads},null,2));}if(results.some(r=>r.status==='FAIL')||errors.length||consoleErrors.length||loads.length)process.exitCode=1;
