import test from 'node:test';import assert from 'node:assert/strict';import {empty,createStore,KEYS} from '../src/store.js';
const m=await import('../src/bible-notes.js').catch(()=>({}));const call=(name,...args)=>{assert.equal(typeof m[name],'function',name);return m[name](...args);};const ref={book:'JHN',chapter:3,from:1,to:1,translation:'otb'},at='2026-10-03T12:00:00Z';
function fixture(){const d=empty();d.journal=[{id:'j',text:'Persönliche Notiz',date:at,ref,pathIds:['p'],reflectionId:'r'}];d.reflections=[{id:'r',text:'Persönliche Notiz',date:at,ref,pathIds:['p']}];d.highlights=[{id:'h',...ref,color:'gold',at}];d.paths=[{id:'p',title:'Weg',steps:[],links:[{id:'l',ref,journalId:'j',reflectionId:'r'}],reviews:[{id:'review',text:'Bleibt',sourceKey:'reflection:r',date:at}],milestones:[]}];return d;}
test('Bible note deletion preserves journal, reference, paths, reviews, highlight and color',()=>{const d=fixture(),before=structuredClone(d);const undo=call('deleteBibleNote',d,'journal','j',at);assert.equal(call('bibleNotes',d,ref).length,0);assert.deepEqual(d.paths,before.paths);assert.deepEqual(d.highlights,before.highlights);assert.equal(d.journal[0].text,before.journal[0].text);assert.deepEqual(d.journal[0].ref,ref);assert.deepEqual(d.journal[0].pathIds,['p']);assert.equal(d.reflections[0].id,'r');call('restoreBibleNote',d,undo);assert.deepEqual(d,before);});
test('Unhighlighted and legacy reflection-only notes remain independently deletable',()=>{const d=fixture();d.highlights=[];d.journal=[];assert.equal(call('bibleNotes',d,ref).length,1);call('deleteBibleNote',d,'reflection','r',at);assert.equal(call('bibleNotes',d,ref).length,0);assert.equal(d.reflections[0].text,'Persönliche Notiz');});
test('Only the explicit selected note is deleted; unrelated note stays active',()=>{const d=fixture();d.journal.push({id:'other',text:'Andere Notiz',date:at,ref});call('deleteBibleNote',d,'journal','j',at);assert.deepEqual(call('bibleNotes',d,ref).map(n=>n.id),['other']);});
test('Undo retains unrelated later reading but refuses to overwrite an edited note',()=>{const d=fixture();const undo=call('deleteBibleNote',d,'journal','j',at);d.reading=ref;call('restoreBibleNote',d,undo);assert.deepEqual(d.reading,ref);const next=call('deleteBibleNote',d,'journal','j',at);d.journal[0].text='Neu bearbeitet';assert.throws(()=>call('restoreBibleNote',d,next),/geändert/);assert.equal(d.journal[0].text,'Neu bearbeitet');});
test('Unrelated legacy reflection with same ID or text must not be marked deleted',()=>{const d=fixture();d.reflections[0].ref={...ref,from:2,to:2};call('deleteBibleNote',d,'journal','j',at);assert.equal(d.reflections[0].bibleNoteDeletedAt,undefined);});
test('Deletion and undo roundtrip through existing V5 store and backups without migration',()=>{const map=new Map([[KEYS.main,JSON.stringify(fixture())]]),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};const store=createStore(storage);const before=store.backup();let undo;store.transact(d=>undo=call('deleteBibleNote',d,'journal','j',at));const exported=store.backup();assert.equal(exported.schemaVersion,5);const next=createStore(storage);assert.equal(call('bibleNotes',next.state,ref).length,0);next.restore(next.prepareImport(exported));assert.equal(call('bibleNotes',next.state,ref).length,0);next.restore(next.prepareImport(before));assert.equal(call('bibleNotes',next.state,ref).length,1);});
