import test from 'node:test';import assert from 'node:assert/strict';import {empty} from '../src/store.js';
const m=await import('../src/continuity.js').catch(()=>({}));
const call=(name,...args)=>{assert.equal(typeof m[name],'function',`Missing continuity behavior: ${name}`);return m[name](...args);};
const ref={book:'JHN',chapter:3,from:1,to:1,translation:'otb'},old='2026-08-01T12:00:00Z',next='2026-09-01T12:00:00Z';
function fixture(){const d=empty();d.paths=[{id:'p',archived:false,steps:[{id:'done',done:true},{id:'open',text:'Listen',done:false}],links:[{ref,date:old}],reviews:[]}];d.journal=[{id:'a',text:'Then',date:old,pathIds:['p'],ref},{id:'b',text:'Now',date:next,pathIds:['p'],ref}];return d;}
test('empty state does not invent reading history',()=>assert.equal(call('readingContext',empty()),null));
test('reading resumes exact range and translation without mutating storage',()=>{const d=fixture();d.reading={...ref,translation:'l1912'};d.events=[{kind:'reading',ref:d.reading,at:old}];const before=JSON.stringify(d);assert.deepEqual(call('readingContext',d),{ref:d.reading,at:old});assert.equal(JSON.stringify(d),before);});
test('invalid reading has no continuation link',()=>{const d=empty();d.reading={book:'JHN',chapter:-1};assert.equal(call('readingContext',d),null);});
test('older linked thought is found by exact context, not text similarity',()=>{const d=fixture();assert.equal(call('previousThought',d,d.journal[1]).id,'a');d.journal[0].pathIds=[];d.journal[0].ref={...ref,from:2,to:2};assert.equal(call('previousThought',d,d.journal[1]),null);});
test('deleted path cannot create false links',()=>{const d=fixture();d.paths=[];delete d.journal[0].ref;delete d.journal[1].ref;assert.equal(call('previousThought',d,d.journal[1]),null);assert.equal(call('pathContext',d,'p'),null);});
test('archived path stays addressable and done step is never current',()=>{const d=fixture();d.paths[0].archived=true;const c=call('pathContext',d,'p');assert.equal(c.path.id,'p');assert.equal(c.step.id,'open');assert.equal(c.thought.id,'b');d.paths[0].steps.forEach(s=>s.done=true);assert.equal(call('pathContext',d,'p').step,null);});
test('explicit review source yields both dates and real content',()=>{const d=fixture();d.reviews=[{id:'rev',sourceKey:'journal:a',date:next,text:'Looking back'}];const pair=call('reviewPairs',d).find(p=>p.review?.id==='rev');assert.equal(pair.before.id,'a');assert.equal(pair.before.date,old);assert.equal(pair.after.date,next);});
test('changed historical content after a review is not presented as its original source',()=>{const d=fixture();d.journal[0].updatedAt='2026-10-01T12:00:00Z';d.reviews=[{id:'rev',sourceKey:'journal:a',date:next,text:'Looking back'}];assert(!call('reviewPairs',d).some(p=>p.review?.id==='rev'));});
test('path reviews retain existing route IDs and ambiguous IDs are suppressed',()=>{const d=fixture();d.paths[0].reviews=[{id:'rev',sourceKey:'path:p',date:next,text:'Review'}];assert.equal(call('allReviews',d)[0].route,'review/rev');d.reviews=[{id:'rev',date:next,text:'Conflicting'}];assert.equal(call('allReviews',d).length,0);});
test('highlight context uses exact references and existing paths only',()=>{const d=fixture(),h={...ref,id:'h',at:old};assert.equal(call('highlightContext',d,h).paths[0].id,'p');assert.equal(call('highlightContext',d,h).notes.length,2);const before=JSON.stringify(d);call('reviewPairs',d);call('highlightContext',d,h);assert.equal(JSON.stringify(d),before);h.from=2;h.to=2;assert.equal(call('highlightContext',d,h).paths.length,0);assert.equal(call('highlightContext',d,h).notes.length,0);});
test('edited current thought never carries its original date into a historical pair',()=>{const d=fixture();d.journal[1].updatedAt='2026-10-01T12:00:00Z';assert(!call('reviewPairs',d).some(p=>p.after.id==='b'));});
test('review context does not assert reflection on text edited after that review',()=>{const d=fixture();d.reviews=[{id:'rev',sourceKey:'journal:a',date:next,text:'Review'}];d.journal[0].updatedAt='2026-10-01T12:00:00Z';assert.equal(call('reviewsFor',d,d.journal[0]).length,0);});
test('legacy reflection with same text/date but different reference is not deduplicated',()=>{const d=fixture();d.reflections=[{id:'distinct',text:d.journal[0].text,date:old,ref:{...ref,from:2,to:2},pathIds:[]}];assert.equal(call('thoughts',d).length,3);});
test('unknown edit timestamps suppress historical attribution',()=>{const d=fixture();d.journal[0].updatedAt='unknown';d.reviews=[{id:'rev',sourceKey:'journal:a',date:next,text:'Review'}];assert.equal(call('reviewsFor',d,d.journal[0]).length,0);assert(!call('reviewPairs',d).some(p=>p.before.id==='a'));});
