import test from 'node:test';import assert from 'node:assert/strict';import {createStore,empty,KEYS} from '../src/store.js';import {deleteJournalEntry,restoreJournalEntry} from '../src/journal-management.js';import {JOURNAL_WRITE_KEY,journalTransaction,recoverJournalWrite} from '../src/journal-storage.js';
function fixture(){const d=empty();d.journal=[{id:'j',text:'Gespeichert',date:'2026-09-01',pathIds:[]}];const draft=JSON.stringify({type:'entry',args:{id:'j'},values:{text:'Noch nicht gespeichert'}}),map=new Map([[KEYS.main,JSON.stringify(d)],[KEYS.draft,draft]]);let fail=()=>false;const storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>{if(fail('set',k))throw new Error('Speicher gesperrt');map.set(k,v);},removeItem:k=>{if(fail('remove',k))throw new Error('Speicher gesperrt');map.delete(k);}};return {d,draft,map,storage,store:createStore(storage),fail:f=>fail=f};}
const remove=f=>journalTransaction(f.store,f.storage,d=>deleteJournalEntry(d,'j'),()=>null);
test('Journal and exact draft deletion/Undo commit together without changing schema',async()=>{const f=fixture(),s=await remove(f);assert(!f.store.state.journal.length);assert(!f.map.has(KEYS.draft));assert(!f.map.has(JOURNAL_WRITE_KEY));await journalTransaction(f.store,f.storage,d=>restoreJournalEntry(d,s),()=>f.draft);assert.deepEqual(f.store.state,f.d);assert.equal(f.map.get(KEYS.draft),f.draft);assert(!f.map.has(JOURNAL_WRITE_KEY));});
test('Selective draft read/remove and recovery-log write failures retain saved data and draft',async()=>{for(const mode of ['remove','log','read']){const f=fixture();if(mode==='read'){const original=f.storage.getItem;f.storage.getItem=k=>{if(k===KEYS.draft)throw new Error('Gesperrt');return original(k);};}else f.fail((op,k)=>mode==='remove'?op==='remove'&&k===KEYS.draft:op==='set'&&k===JOURNAL_WRITE_KEY);await assert.rejects(remove(f));assert.deepEqual(f.store.state,f.d);assert.equal(f.map.get(KEYS.draft),f.draft);}});
test('Main write failure rolls the draft back; no partial saved deletion',async()=>{const f=fixture();f.fail((op,k)=>op==='set'&&k===KEYS.main);await assert.rejects(remove(f));assert.deepEqual(f.store.state,f.d);assert.equal(f.map.get(KEYS.draft),f.draft);assert(!f.map.has(JOURNAL_WRITE_KEY));});
test('Undo draft write failure leaves deletion intact and supports safe retry',async()=>{const f=fixture(),snap=await remove(f);f.fail((op,k)=>op==='set'&&k===KEYS.draft);await assert.rejects(journalTransaction(f.store,f.storage,d=>restoreJournalEntry(d,snap),()=>f.draft));assert(!f.store.state.journal.length);assert(!f.map.has(KEYS.draft));f.fail(()=>false);await journalTransaction(f.store,f.storage,d=>restoreJournalEntry(d,snap),()=>f.draft);assert.deepEqual(f.store.state,f.d);assert.equal(f.map.get(KEYS.draft),f.draft);});
test('Interrupted failed write recovers exact draft on next load from durable recovery record',async()=>{const f=fixture();f.fail((op,k)=>op==='set'&&[KEYS.main,KEYS.draft].includes(k));await assert.rejects(remove(f),/gesichert/);assert(f.map.has(JOURNAL_WRITE_KEY));assert.deepEqual(f.store.state,f.d);f.fail(()=>false);await recoverJournalWrite(f.storage);assert.equal(f.map.get(KEYS.draft),f.draft);assert(!f.map.has(JOURNAL_WRITE_KEY));assert.deepEqual(createStore(f.storage).state,f.d);});
test('Interrupted committed cleanup recovers without resurrecting deleted data',async()=>{const f=fixture();f.fail((op,k)=>op==='remove'&&k===JOURNAL_WRITE_KEY);await remove(f);assert(f.map.has(JOURNAL_WRITE_KEY));f.fail(()=>false);await recoverJournalWrite(f.storage);assert(!f.map.has(KEYS.draft));assert(!createStore(f.storage).state.journal.length);assert(!f.map.has(JOURNAL_WRITE_KEY));});
test('Recovery never overwrites a newer unrelated draft',async()=>{const f=fixture();f.fail((op,k)=>op==='set'&&[KEYS.main,KEYS.draft].includes(k));await assert.rejects(remove(f));f.fail(()=>false);f.map.set(KEYS.draft,'newer draft');await assert.rejects(recoverJournalWrite(f.storage),/neuerer/);assert.equal(f.map.get(KEYS.draft),'newer draft');assert.deepEqual(createStore(f.storage).state,f.d);});
