import fs from 'node:fs';import path from 'node:path';import {chromium} from 'playwright';import {coreFixture} from './core-depth-fixture.mjs';import {empty,KEYS} from '../src/store.js';
const base=process.env.QA_URL||'http://127.0.0.1:4220',out=process.env.QA_OUT||'qa-output/premium-final/before';fs.mkdirSync(out,{recursive:true});
export function premiumFixture(){const d=coreFixture();d.journal[1].date='2026-10-02T12:00:00.000Z';d.reviews[0].date='2026-10-03T12:00:00.000Z';const ref={book:'JHN',chapter:3,from:1,to:1,translation:'otb'};d.journal.unshift({id:'premium-note',reflectionId:'premium-mirror',type:'Bibel',subtype:'Reflexion',text:'Ich möchte mir Zeit nehmen, um wirklich zuzuhören.\nDiese Stelle begleitet meinen Weg.',date:'2026-10-03T08:00:00.000Z',ref,pathIds:['core-path']});d.reflections.push({id:'premium-mirror',text:d.journal[0].text,date:d.journal[0].date,ref,pathIds:['core-path']});d.paths[0].links.push({id:'entry-premium-note',kind:'reflection',journalId:'premium-note',reflectionId:'premium-mirror',label:'Johannes 3,1',ref,date:d.journal[0].date});return d;}
if(process.env.QA_FIXTURE_ONLY!=='1'){
const b=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox',...(process.env.FAITHPATH_PROXY_SPKI?['--ignore-certificate-errors-spki-list='+process.env.FAITHPATH_PROXY_SPKI]:[])]});const shots=[],errors=[];
async function context(w,h,text=100,fresh=false,safe=false){const c=await b.newContext({viewport:{width:w,height:h},serviceWorkers:'block'});await c.addInitScript(({data,KEYS,text,safe})=>{if(!localStorage.getItem(KEYS.main)){localStorage.setItem(KEYS.main,JSON.stringify(data));localStorage.setItem(KEYS.onboard,'done');}document.addEventListener('DOMContentLoaded',()=>{document.documentElement.style.fontSize=text+'%';if(safe){document.documentElement.style.setProperty('--safe-top','47px');document.documentElement.style.setProperty('--safe-bottom','34px');}});},{data:fresh?empty():premiumFixture(),KEYS,text,safe});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));return {c,p};}
async function route(p,r){await p.goto(base+'/#'+r,{waitUntil:'networkidle'});await p.locator('#main h1').waitFor();if(r.startsWith('read/'))await p.locator('.verse').first().waitFor();const warning=p.locator('.toast.error.visible').filter({hasText:'Offline-Vorbereitung konnte nicht abgeschlossen'});if(await warning.count())await warning.getByRole('button',{name:'Meldung schließen',exact:true}).click();}
async function shot(p,n,full=false){const file=path.join(out,n+'.png');await p.screenshot({path:file,fullPage:full});shots.push({name:n,file});}
try{const {c,p}=await context(390,844);for(const [r,n]of [['today','01-today'],['bible','02-bible'],['read/JHN/3/otb','03-reader'],['marks','04-marks'],['journal','05-journal'],['entry/premium-note','06-journal-detail'],['paths','10-paths'],['path/core-path','11-path-detail'],['reviews','12-reviews'],['history','13-history'],['more','14-more'],['guidance','15-topics'],['plans','16-guided'],['discover','17-discover'],['quizzes','18-quiz']]){await route(p,r);await shot(p,n);await shot(p,n+'-full',true);}await route(p,'more');await p.locator('#menu-toggle').click();await shot(p,'19-menu');await p.keyboard.press('Escape');await route(p,'entry/premium-note');if(await p.locator('[data-action=delete-journal]').count()){await p.locator('.entry-options summary').click();await p.locator('[data-action=delete-journal]').click();await shot(p,'07-journal-delete');await p.getByRole('dialog').getByRole('button',{name:'Journaleintrag löschen',exact:true}).click();await p.waitForFunction(()=>!document.querySelector('dialog').open);await p.waitForFunction(()=>location.hash==='#journal'&&!!document.querySelector('.journal-month'));await shot(p,'08-journal-after-delete');await p.getByRole('button',{name:'Rückgängig',exact:true}).click();await p.waitForFunction(KEYS=>JSON.parse(localStorage.getItem(KEYS.main)).journal.some(j=>j.id==='premium-note'),KEYS);await p.locator('.journal-page-entry').first().waitFor();await shot(p,'09-journal-undo');}else shots.push({name:'07-journal-delete',not_available_in_baseline:true});await route(p,'entry/premium-note');if(await p.locator('.entry-options summary').count())await p.locator('.entry-options summary').click();await p.getByRole('button',{name:'Bearbeiten',exact:true}).click();await shot(p,'20-journal-edit');await c.close();
for(const [w,h,t,safe]of[[320,568,100,false],[320,568,200,false],[390,844,200,false],[768,1024,100,false],[1440,1000,100,false],[390,844,100,true]]){const{c,p}=await context(w,h,t,false,safe);for(const r of ['today','journal','more','read/JHN/3/otb','bible']){await route(p,r);await shot(p,`${w}-${t}-${safe?'safe-':''}${r.split('/')[0]}`);}if(t===200){await route(p,'read/JHN/3/otb');await p.locator('[data-v="1"]').click();await shot(p,`${w}-200-selection`);await p.getByRole('button',{name:'Markieren',exact:true}).click();await shot(p,`${w}-200-palette`);}await c.close();}const fresh=await context(390,844,100,true);for(const r of ['today','journal']){await route(fresh.p,r);await shot(fresh.p,'new-'+r);}await fresh.c.close();}finally{await b.close();fs.writeFileSync(path.join(out,'screenshots.json'),JSON.stringify({base,shots,errors},null,2));}}
