import test from 'node:test';import assert from 'node:assert/strict';import {empty,createStore,KEYS} from '../src/store.js';import {treeLevel,timeline} from '../src/domain.js';import {reviewPairs,highlightContext} from '../src/continuity.js';
const m=await import('../src/journal-management.js').catch(()=>({}));const call=(name,...args)=>{assert.equal(typeof m[name],'function',name+' must exist');return m[name](...args);};const ref={book:'JHN',chapter:3,from:1,to:1,translation:'otb'};
function fixture(){const d=empty();d.journal=[{id:'j',reflectionId:'r',text:'Meine Worte',date:'2026-09-01',type:'Bibel',subtype:'Gedanken',ref,pathIds:['p'],custom:{keep:true}},{id:'other',text:'Anderer Eintrag',date:'2026-08-01',pathIds:['p']}];d.reflections=[{id:'r',text:'Meine Worte',date:'2026-09-01',ref,pathIds:['p']}];d.highlights=[{id:'h',...ref,color:'gold',at:'2026-09-01'}];d.paths=[{id:'p',title:'Vertrauen',steps:[{id:'s',text:'Zuhören',done:false}],links:[{id:'l',kind:'reflection',journalId:'j',reflectionId:'r',ref,date:'2026-09-01'}],reviews:[{id:'pr',text:'Eigenständiger Rückblick',sourceKey:'reflection:r',date:'2026-10-02'}],milestones:[{id:'m',reviewId:'pr',text:'Dokumentiert',date:'2026-10-02'}]}];d.reviews=[{id:'rv',text:'Heute sehe ich es anders.',sourceKey:'journal:j',date:'2026-10-02'}];d.dismissedGaps={'journal:j':'2026-10-02','path:p':'2026-10-02'};d.reminderSnoozes={'reflection:r':'2026-10-02'};return d;}
test('Journal deletion physically removes exactly the entry and explicit mirror, preserving personal data',()=>{const d=fixture(),before=structuredClone(d),level=treeLevel(d);call('deleteJournalEntry',d,'j');assert.deepEqual(d.journal.map(x=>x.id),['other']);assert.equal(d.reflections.length,0);assert.deepEqual(d.highlights,before.highlights);assert.deepEqual(d.paths[0].steps,before.paths[0].steps);assert.deepEqual(d.paths[0].milestones,before.paths[0].milestones);assert.equal(d.paths[0].title,'Vertrauen');assert.equal(treeLevel(d),level);assert.equal(d.reviews[0].text,before.reviews[0].text);});
test('Deletion cleans typed direct links, review sources and reminder metadata without dead pairs',()=>{const d=fixture();call('deleteJournalEntry',d,'j');assert.equal(d.paths[0].links[0].journalId,undefined);assert.equal(d.paths[0].links[0].reflectionId,undefined);assert.equal(d.paths[0].links[0].kind,'verse');assert.deepEqual(d.paths[0].links[0].ref,ref);assert.equal(d.reviews[0].sourceKey,undefined);assert.equal(d.paths[0].reviews[0].sourceKey,undefined);assert.equal(d.dismissedGaps['journal:j'],undefined);assert.equal(d.reminderSnoozes['reflection:r'],undefined);assert.equal(d.dismissedGaps['path:p'],'2026-10-02');assert.equal(reviewPairs(d).length,0);assert.equal(highlightContext(d,d.highlights[0]).notes.length,0);assert(!timeline(d).some(x=>x.route==='entry/j'||x.route==='reflection/r'));});
test('No-reference journal path link disappears but standalone verse and independent same-ID reflection stay',()=>{const d=fixture();d.paths[0].links.push({id:'plain',kind:'reflection',journalId:'j'});d.reflections.push({id:'j',text:'Unabhängige Worte',date:'2026-09-02',ref});call('deleteJournalEntry',d,'j');assert.equal(d.paths[0].links.some(x=>x.id==='plain'),false);assert.equal(d.reflections[0].id,'j');assert.equal(d.reflections[0].text,'Unabhängige Worte');});
test('Ambiguous, changed and shared mirrors are never silently removed',()=>{for(const mode of ['text','date','ref','shared']){const d=fixture();if(mode==='text')d.reflections[0].text='Unabhängig';if(mode==='date')d.reflections[0].date='2026-09-02';if(mode==='ref')d.reflections[0].ref={...ref,from:2,to:2};if(mode==='shared')d.journal[1].reflectionId='r';const old=structuredClone(d.reflections);call('deleteJournalEntry',d,'j');assert.deepEqual(d.reflections,old,mode);}});
test('Undo restores all entry data and valid references, retaining unrelated newer records and settings',()=>{const d=fixture(),before=structuredClone(d);const undo=call('deleteJournalEntry',d,'j');d.journal.unshift({id:'new',text:'Neu',date:'2026-10-03'});d.paths[0].steps.push({id:'new-step',text:'Neu',done:false});d.paths[0].links.push({id:'new-link',ref:{...ref,from:2,to:2}});d.settings.reader='large';d.reading=ref;call('restoreJournalEntry',d,undo);assert.deepEqual(d.journal.find(x=>x.id==='j'),before.journal[0]);assert.deepEqual(d.reviews,before.reviews);assert.equal(d.journal[0].id,'new');assert.equal(d.paths[0].steps.at(-1).id,'new-step');assert.equal(d.paths[0].links.at(-1).id,'new-link');assert.equal(d.settings.reader,'large');assert.deepEqual(d.reading,ref);});
test('Undo detects changed references or reused IDs atomically without overwriting newer data',()=>{for(const mode of ['review','id','path']){const d=fixture();const undo=call('deleteJournalEntry',d,'j');if(mode==='review')d.reviews[0].sourceKey='journal:other';if(mode==='id')d.journal.push({id:'j',text:'Neu'});if(mode==='path')d.paths=[];const after=structuredClone(d);assert.throws(()=>call('restoreJournalEntry',d,undo),/inzwischen|neuere|verändert/);assert.deepEqual(d,after);}});
test('Only the exact journal or matching mirrored-note draft is selected for cleanup',()=>{const d=fixture(),undo=call('deleteJournalEntry',d,'j');assert(call('journalDraftMatches',{type:'entry',args:{id:'j'}},undo));assert(call('journalDraftMatches',{type:'note',args:{id:'r'}},undo));assert(!call('journalDraftMatches',{type:'note',args:{id:'j'}},undo));assert(!call('journalDraftMatches',{type:'entry',args:{id:'other'}},undo));});
test('Physical deletion and Undo roundtrip through V5 backup without migration or zombie records',()=>{const map=new Map([[KEYS.main,JSON.stringify(fixture())]]),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};const st=createStore(storage),old=st.backup();let undo;st.transact(d=>undo=call('deleteJournalEntry',d,'j'));const deleted=st.backup();assert.equal(deleted.schemaVersion,5);const next=createStore(storage);next.restore(next.prepareImport(deleted));assert(!next.state.journal.some(x=>x.id==='j'));assert.equal(highlightContext(next.state,next.state.highlights[0]).notes.length,0);next.restore(next.prepareImport(old));assert.equal(next.state.journal[0].id,'j');});

test('Changing journal path only changes chosen entry association, preserving unrelated notes and verse link',()=>{const d=fixture();d.paths.push({id:'p2',title:'Anderer Weg',links:[],steps:[],reviews:[],milestones:[]});call('setJournalPath',d,'j','p2');assert.deepEqual(d.journal[0].pathIds,['p2']);assert.deepEqual(d.journal[1].pathIds,['p']);assert.deepEqual(d.reflections[0].pathIds,['p2']);assert.deepEqual(d.paths[0].links[0].ref,ref);assert.equal(d.paths[0].links[0].journalId,undefined);});
test('Path management leaves an inconsistent independent reflection intact',()=>{const d=fixture();d.reflections[0].text='Unabhängiger Text';const before=structuredClone(d.reflections);call('setJournalPath',d,'j','');assert.deepEqual(d.reflections,before);});
test('Path draft cleanup, reconnect IDs and missing dependency Undo remain safe',()=>{const d=fixture();call('setJournalPath',d,'j','');call('setJournalPath',d,'j','p');assert.equal(new Set(d.paths[0].links.map(l=>l.id)).size,d.paths[0].links.length);const undo=call('deleteJournalEntry',d,'j');assert(call('journalDraftMatches',{type:'journal-path',args:{id:'j'}},undo));const x=fixture();x.paths[0].links=[];const snap=call('deleteJournalEntry',x,'j');x.paths=[];const before=structuredClone(x);assert.throws(()=>call('restoreJournalEntry',x,snap));assert.deepEqual(x,before);});
