import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {validateFinalNtQuiz} from './validate-nt-quiz.mjs';
import {auditContent} from './validate-content.mjs';
import {createRuntimeModel} from '../src/runtime-model.js';
import {BUILD} from '../src/version.js';
const hash = v => crypto.createHash('sha256').update(v).digest('hex');
const read = f => JSON.parse(fs.readFileSync(f,'utf8'));
validateFinalNtQuiz();
const {index,report} = auditContent();
if(report.errors.length) throw new Error(report.errors.join('\n'));
createRuntimeModel([read('data/index.json'),read('data/stories.json'),index,read('data/faithpath-content-index.json'),read('data/nachlese-stories.json'),read('data/nachlese-questions.json'),read('data/faithpath-nachlese-story-flow.json')]);
const files = dir => fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(path.join(dir,e.name)):[path.join(dir,e.name)]).sort();
const candidateFiles=Object.fromEntries(files('data').filter(p=>p.endsWith('.json')&&!p.startsWith('data/audit/')).map(p=>[p,hash(fs.readFileSync(p))]));
const contentHash=hash(JSON.stringify(candidateFiles));
const out=process.env.FAITHPATH_OUT||'dist', release=`releases/${BUILD}`;
if(!/^FP4-\d{8}-[A-Z][A-Z0-9-]*$/.test(BUILD)||BUILD==='FP4-20260916-F')throw new Error('New build ID required');
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(`${out}/${release}`,{recursive:true});
fs.cpSync('data',`${out}/${release}/data`,{recursive:true,filter:p=>!p.startsWith('data/audit')});
fs.writeFileSync(`${out}/${release}/data/reference-index.json`,JSON.stringify(index));
fs.writeFileSync(`${out}/${release}/data/content-report.json`,JSON.stringify(report,null,2));
fs.cpSync('src',`${out}/${release}/src`,{recursive:true});fs.copyFileSync('styles.css',`${out}/${release}/styles.css`);
for(const d of ['data/bibles','trees','icons'])fs.cpSync(d,`${out}/${d}`,{recursive:true});
for(const f of ['manifest.webmanifest','_headers','_redirects','404.html'])fs.copyFileSync(f,`${out}/${f}`);
fs.writeFileSync(`${out}/index.html`,fs.readFileSync('index.html','utf8').replace('./styles.css',`./${release}/styles.css`).replace('./src/app.js',`./${release}/src/app.js`));
fs.writeFileSync(`${out}/BUILD.txt`,`${BUILD}\nBranch: ${process.env.BRANCH || 'local (BRANCH unset)'}\n`);
fs.writeFileSync(`${out}/candidate-integrity.json`,JSON.stringify({build:BUILD,content_hash:contentHash,algorithm:'SHA256(JSON.stringify(sorted path-to-SHA256 map)); data/**/*.json excluding data/audit/**',files:candidateFiles},null,2));
const assets=files(out).filter(f=>!f.endsWith('_headers')&&!f.endsWith('_redirects')).map(f=>'./'+path.relative(out,f)).sort();
fs.writeFileSync(`${out}/sw.js`,fs.readFileSync('scripts/sw-template.js','utf8').replace('__BUILD__',BUILD).replace('__ASSETS__',JSON.stringify(assets)));
const hashes=Object.fromEntries(files(out).map(f=>[path.relative(out,f),hash(fs.readFileSync(f))]));
fs.writeFileSync(`${out}/release-integrity.json`,JSON.stringify({build:BUILD,content_hash:contentHash,build_hash:hash(JSON.stringify(hashes)),files:hashes},null,2));
console.log(JSON.stringify({build:BUILD,files:Object.keys(hashes).length+1,content_hash:contentHash,build_hash:hash(JSON.stringify(hashes))}));
