// Read-only selectors over existing local records. No inferred meaning or storage writes.
import {sameRef,time} from './domain.js';
const dated = x => time(x?.date) != null;
const unchangedBefore = (x,at) => !x.updatedAt || (time(x.updatedAt)!=null && time(x.updatedAt)>=time(x.date) && time(x.updatedAt)<=time(at));
const originalText = x => unchangedBefore(x,x.date);
const newest = xs => xs.slice().sort((a,b)=>time(b.date)-time(a.date));
const route = (kind,id) => kind+'/'+encodeURIComponent(id);
export function readingContext(data){const r=data.reading;if(!r||!r.book||!Number.isInteger(+r.chapter)||+r.chapter<1||!['otb','l1912'].includes(r.translation||'otb'))return null;const ev=(data.events||[]).filter(x=>x.kind==='reading'&&sameRef(x.ref,r)&&time(x.at)!=null).sort((a,b)=>time(b.at)-time(a.at))[0];return {ref:r,at:ev?.at||null};}
export function thoughts(data){const js=(data.journal||[]).map(x=>({...x,kind:'journal',route:route('entry',x.id)}));const rs=(data.reflections||[]).filter(r=>!js.some(j=>j.reflectionId===r.id)).map(x=>({...x,kind:'reflection',route:route('reflection',x.id)}));return newest([...js,...rs].filter(x=>dated(x)&&x.text?.trim()));}
const exactContext=(data,a,b)=>sameRef(a.ref,b.ref)||(a.pathIds||[]).some(id=>(b.pathIds||[]).includes(id)&&data.paths.some(p=>p.id===id));
export function previousThought(data,current){if(!dated(current))return null;return thoughts(data).find(x=>x.id!==current.id&&x.id!==current.reflectionId&&time(x.date)<time(current.date)&&unchangedBefore(x,current.date)&&exactContext(data,x,current))||null;}
export function allReviews(data){const xs=[...(data.reviews||[]),...data.paths.flatMap(p=>(p.reviews||[]).map(r=>({...r,pathId:p.id})))];return newest(xs.filter(r=>dated(r)&&r.text?.trim()&&xs.filter(x=>x.id===r.id).length===1).map(r=>({...r,route:route('review',r.id)})));}
export function reviewsFor(data,item,kind='journal'){const aliases=kind==='journal'?['journal','j']:kind==='reflection'?['reflection','r']:[kind];const keys=aliases.map(k=>k+':'+item.id);if(item.reflectionId)keys.push('reflection:'+item.reflectionId,'r:'+item.reflectionId);return allReviews(data).filter(r=>keys.includes(r.sourceKey)&&time(r.date)>time(item.date||item.at)&&unchangedBefore({...item,date:item.date||item.at},r.date));}
export function reviewPairs(data){const pairs=[];for(const r of allReviews(data)){const [kind,...parts]=String(r.sourceKey||'').split(':'),id=parts.join(':');const collection=['journal','j'].includes(kind)?data.journal:['reflection','r'].includes(kind)?data.reflections:[];const xs=collection.filter(x=>x.id===id);const x=xs.length===1?xs[0]:null;if(x?.text&&dated(x)&&time(x.date)<time(r.date)&&unchangedBefore(x,r.date))pairs.push({before:{...x,date:x.updatedAt||x.date,route:route(['journal','j'].includes(kind)?'entry':'reflection',x.id)},after:r,review:r,kind:'explicit-review'});}
for(const current of thoughts(data)){const before=previousThought(data,current);if(before&&originalText(before)&&originalText(current)&&!pairs.some(p=>p.before.id===before.id&&p.after.id===current.id))pairs.push({before,after:current,kind:'shared-context'});}return pairs.sort((a,b)=>(b.kind==='explicit-review')-(a.kind==='explicit-review')||time(b.after.date)-time(a.after.date));}
export function pathContext(data,pid){const p=data.paths.find(p=>p.id===pid);if(!p)return null;const ts=thoughts(data).filter(j=>j.pathIds?.includes(pid));const ls=(p.links||[]).filter(l=>l.ref&&time(l.date)!=null).slice().sort((a,b)=>time(b.date)-time(a.date));const reading=readingContext(data);return {path:p,step:p.steps.find(x=>!x.done)||null,thought:ts[0]||null,reference:ls[0]?.ref||null,reading:reading&&ls.some(l=>sameRef(l.ref,reading.ref))?reading:null,review:allReviews(data).find(r=>r.pathId===pid||r.sourceKey==='path:'+pid)||null};}
export function highlightContext(data,h){const notes=thoughts(data).filter(j=>sameRef(j.ref,h)),paths=data.paths.filter(p=>p.links.some(l=>sameRef(l.ref,h))),reviews=[...reviewsFor(data,h,'highlight'),...notes.flatMap(j=>reviewsFor(data,j,j.kind))];return {notes:notes.filter(j=>!j.bibleNoteDeletedAt),paths,review:newest(reviews)[0]||null};}
