import {journeySummary,exploredChapters} from './bible-journey.js';
import {treeBranches,branchSlots,pathEvidence} from './tree-branches.js';
import {THEMES,themeId} from './themes.js';
const e=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const route=(data,book,chapter)=>`read/${book}/${chapter}/${data.translation||'otb'}`;
const link=(label,r,cls='text-link',extra='')=>`<a class="${cls}" href="#${e(r)}" ${extra}>${e(label)}</a>`;
export const sword=()=>'<svg class="journey-symbol" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m5 19 3-3m-2-3 5 5M9 15l9-9 1-3-3 1-9 9M3 21l2-2"/></svg>';
export function journeyAcknowledgement(data,books,ref){const done=exploredChapters(data,books).has(ref.book+':'+ref.chapter),name=books.find(b=>b.code===ref.book)?.name||ref.book;return `<section class="journey-acknowledgement" aria-live="polite" ${done?'':'hidden'}>${sword()}<div><span class="overline">Kapitel erkundet</span><p>${e(name)} ${ref.chapter} ist jetzt Teil deiner Bibelreise.</p>${link('Deine Bibelreise ansehen','bible-journey/'+ref.book)}</div></section>`;}
export function journeyView(data,books,code=''){
 const x=journeySummary(data,books),book=x.books.find(b=>b.code===code);if(code&&!book)return null;
 const reading=x.reading;
 if(book){const known=new Set(book.explored.map(e=>e.chapter)),next=book.current&&!known.has(book.current)?book.current:Array.from({length:book.chapters},(_,i)=>i+1).find(c=>!known.has(c))||book.current||1;
  return {title:book.name,body:`<p class="journey-reading-state">${known.size} von ${book.chapters} Kapiteln erkundet${known.size===book.chapters?' · vollständig erkundet':''}</p>${link('Hier weiter',route(data,code,next),'button primary')}<ol class="journey-chapters">${Array.from({length:book.chapters},(_,i)=>{const c=i+1,done=known.has(c),current=book.current===c;return `<li>${link('Kapitel '+c,route(data,code,c),'journey-chapter-link',`aria-label="${e(book.name)} Kapitel ${c}, ${done?'erkundet':'noch nicht erkundet'}${current?', zuletzt geöffnet':''}"`)}<span class="meta">${done?'✓ Erkundet':'Noch nicht erkundet'}${current?' · zuletzt geöffnet':''}</span></li>`;}).join('')}</ol>`};
 }
 return {title:'Deine Bibelreise',body:`<p class="journey-intro">${sword()} Was du gelesen hast, bleibt sichtbar. Ohne Bewertung deines Glaubens.</p><dl class="journey-facts"><div><dt>Kapitel erkundet</dt><dd>${x.chapters}</dd></div><div><dt>Bücher begonnen</dt><dd>${x.begunBooks}</dd></div><div><dt>Bücher vollständig erkundet</dt><dd>${x.completedBooks}</dd></div></dl>${reading?`<div class="continuity-strip"><span class="overline">Hier weiter</span>${link((books.find(b=>b.code===reading.book)?.name||reading.book)+' '+reading.chapter,route(data,reading.book,reading.chapter))}</div>`:''}${[ ['Altes Testament',x.books.slice(0,39)],['Neues Testament',x.books.slice(39)]].map(([title,bs])=>`<section class="journey-testament"><h2>${title}</h2><ul class="journey-books">${bs.map(b=>`<li>${link(b.name,'bible-journey/'+b.code,'journey-book-link')}<span class="meta">${b.explored.length} von ${b.chapters} Kapiteln erkundet${b.explored.length===b.chapters?' · vollständig':''}</span></li>`).join('')}</ul></section>`).join('')}`};
}
export function treeBranchView(data,stage){
 const {visible,other}=treeBranches(data,stage),slots=branchSlots[stage]||[];
 const scene=`<div class="tree-branch-scene branch-stage-${stage}"><img src="trees/tree-stage-${stage+1}.webp" alt="Olivenbaum" width="${stage===2?784:1086}" height="${stage===2?1168:1448}">${visible.length?`<svg class="tree-branch-overlay" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">${visible.map((v,i)=>{const [x,y]=slots[i];return `<path d="M50 68 Q50 ${y+8} ${x} ${y}" class="${v.hasReview?'branch-reviewed':''}"/>`;}).join('')}</svg>${visible.map((v,i)=>link(i+1,'path/'+encodeURIComponent(v.path.id),'tree-branch-hit',`data-slot="${i}" data-path-id="${e(v.path.id)}" aria-label="Weg ${e(v.path.title)}, öffnen"`)).join('')}`:''}</div>`;
 const item=(v,i)=>`<li>${link((i?i+'. ':'')+v.path.title,'path/'+encodeURIComponent(v.path.id),'branch-path-link')}<span class="meta">${v.hasMilestone?'Entwicklung selbst festgehalten':v.hasReview?'Rückblick festgehalten':'Persönliche Geschichte festgehalten'}${v.path.archived?' · archiviert':''}</span></li>`;
 return `<figure class="tree-figure interactive-tree">${scene}<figcaption>Ruhende Wege und schwierige Zeiten nehmen deiner Geschichte nichts weg.</figcaption></figure>${visible.length?`<section class="tree-paths"><h2>Wege an deinem Baum</h2><ol>${visible.map((v,i)=>item(v,i+1)).join('')}</ol></section>`:''}${other.length?`<section class="tree-other-paths"><h2>Weitere Wege</h2><ul>${other.map(v=>item(v,0)).join('')}</ul></section>`:''}`;
}
export function pathFacts(data,pid){const x=pathEvidence(data,pid);if(!x?.documented)return '';return `<p class="path-history-facts meta" aria-label="Zu diesem Weg festgehalten">${x.thoughts.length} Gedanken · ${x.steps.length} Schritte · ${x.reviews.length} Rückblicke</p>`;}
export function themePicker(data){const selected=themeId(data);return `<section class="section appearance-section"><h2 id="appearance-title">Darstellung</h2><p>Eine andere Atmosphäre. Deine Geschichte bleibt dieselbe.</p><div class="theme-picker" role="radiogroup" aria-labelledby="appearance-title">${THEMES.map(t=>`<button type="button" role="radio" aria-checked="${t.id===selected}" tabindex="${t.id===selected?0:-1}" data-action="set-theme" data-theme-id="${t.id}" class="theme-tile"><span class="theme-preview" data-preview="${t.id}" aria-hidden="true"><span>Aa</span><i></i></span><span>${e(t.label)}</span>${t.id===selected?'<span class="theme-selected">✓ Ausgewählt</span>':''}</button>`).join('')}</div></section>`;}
